name: hl-weather-box
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 min
  push:
    branches: master
jobs:
  hl-weather:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       with:
          darksky_key: ${{ secrets.darksky_key }}
          location: ${{ secrets.location }}
          location2: ${{ secrets.location2 }}
          gh_token: ${{ secrets.gh_token }}
          gist_id: ${{ secrets.gist_id }}
